exports.industries = {
  "Information Technology and Services": 1,
  "Computer Software": 1,
  "Software": 1,
  "Marketing and Advertising": 2,
  "Internet": 1,
  "Financial Services": 3,
  "Real Estate": 4,
  "Mobile": 1,
  "Telecommunications": 5,
  "Management Consulting": 6,
  "E-Commerce": 7,
  "Staffing and Recruiting": 8,
  "Curated Web": 1,
  "Advertising": 2,
  "Non-Profit Organization Management": 9,
  "Design": 10,
  "Law Practice": 11,
  "Social Media": 1,
  "Consulting": 12,
  "Higher Education": 22,
  "Construction": 14,
  "Hospital & Health Care": 15,
  "Insurance": 16,
  "Human Resources": 8,
  "Publishing": 17,
  "Retail": 18,
  "Enterprise Software": 1,
  "Entertainment": 19,
  "Banking": 3,
  "Biotechnology": 20,
  "Automotive": 21,
  "Web Development": 1,
  "Education Management": 22,
  "Education": 22,
  "Games": 1,
  "Hospitality": 23,
  "Electrical/Electronic Manufacturing": 24,
  "Government Administration": 25,
  "Investment Management": 26,
  "Finance": 3,
  "Public Relations and Communications": 2,
  "SaaS": 1,
  "Music": 101,
  "Architecture & Planning": 28,
  "Accounting": 3,
  "Pharmaceuticals": 15,
  "Consumer Goods": 30,
  "Oil & Energy": 82,
  "Professional Training & Coaching": 32,
  "Medical Devices": 15,
  "Sports": 33,
  "Technology": 1,
  "Apps": 1,
  "SEO": 1,
  "Web Design": 1,
  "Analytics": 34,
  "Broadcast Media": 35,
  "Printing": 36,
  "Sales and Marketing": 2,
  "Health, Wellness and Fitness": 15,
  "Leisure, Travel & Tourism": 105,
  "Media Production": 35,
  "Mechanical or Industrial Engineering": 39,
  "Research": 40,
  "Fund-Raising": 41,
  "Semiconductors": 24,
  "Legal Services": 11,
  "Venture Capital & Private Equity": 41,
  "Search": 42,
  "Hardware + Software": 24,
  "Health and Wellness": 15,
  "Internet Marketing": 2,
  "Web Hosting": 1,
  "Environmental Services": 43,
  "News": 44,
  "Consumer Electronics": 45,
  "Public Relations": 2,
  "Market Research": 46,
  "Networking": 47,
  "Online Media": 35,
  "Health Care": 15,
  "Photography": 48,
  "Cloud Computing": 1,
  "Media": 35,
  "Food & Beverages": 49,
  "Logistics and Supply Chain": 50,
  "Fashion": 51,
  "Android": 1,
  "Travel": 105,
  "Video": 52,
  "Wireless": 1,
  "Security": 53,
  "Startups": 54,
  "Computer & Network Security": 1,
  "iPhone": 1,
  "Transportation/Trucking/Railroad": 50,
  "Civil Engineering": 55,
  "Computer Hardware": 24,
  "Apparel & Fashion": 51,
  "Information Technology": 1,
  "Information Services": 1,
  "Computer Games": 56,
  "Marketplaces": 57,
  "Business Services": 58,
  "Services": 59,
  "Machinery": 60,
  "Computer Networking": 1,
  "Manufacturing": 24,
  "Social Network Media": 1,
  "Wholesale": 2,
  "Food Production": 49,
  "Renewables & Environment": 61,
  "Newspapers": 17,
  "Building Materials": 62,
  "Investment Banking": 3,
  "Graphic Design": 1,
  "Clean Technology": 63,
  "Content": 17,
  "E-Learning": 64,
  "Defense & Space": 65,
  "Big Data": 1,
  "Industrial Automation": 1,
  "Digital Media": 17,
  "Utilities": 66,
  "Restaurants": 49,
  "Furniture": 67,
  "Chemicals": 68,
  "Brand Marketing": 2,
  "iOS": 1,
  "Events": 69,
  "Airlines/Aviation": 65,
  "Social Media Marketing": 2,
  "Legal": 11,
  "Recruiting": 8,
  "Motion Pictures and Film": 70,
  "FinTech": 71,
  "CRM": 72,
  "Religious Institutions": 73,
  "Consumer Services": 74,
  "Commercial Real Estate": 4,
  "Aviation & Aerospace": 65,
  "Security and Investigations": 53,
  "EdTech": 75,
  "Mining & Metals": 76,
  "Primary/Secondary Education": 22,
  "Business Supplies and Equipment": 77,
  "Local Businesses": 77,
  "Outsourcing/Offshoring": 78,
  "Messaging": 1,
  "Enterprises": 77,
  "International Trade and Development": 79,
  "Collaboration": 80,
  "Facilities Services": 63,
  "Location Based Services": 1,
  "B2B": 77,
  "Reviews and Recommendations": 81,
  "Plastics": 82,
  "Payments": 1,
  "Packaging and Containers": 83,
  "Facebook Applications": 1,
  "Video Streaming": 1,
  "Business Intelligence": 77,
  "Civic & Social Organization": 1,
  "Online Shopping": 1,
  "Medical": 15,
  "Blogging Platforms": 1,
  "Maritime": 84,
  "Textiles": 51,
  "Museums and Institutions": 85,
  "Transportation": 50,
  "Web Tools": 1,
  "Small and Medium Businesses": 77,
  "Performing Arts": 86,
  "Shopping": 87,
  "Sporting Goods": 33,
  "Medical Practice": 15,
  "Hardware": 24,
  "Big Data Analytics": 1,
  "Outsourcing": 78,
  "Mobile Commerce": 2,
  "Wine and Spirits": 49,
  "iPad": 1,
  "Coupons": 88,
  "Training": 8,
  "Project Management": 1,
  "Employment": 8,
  "Local": 77,
  "Non Profit": 9,
  "Television": 17,
  "Customer Service": 90,
  "Translation and Localization": 91,
  "Fitness": 33,
  "Social Commerce": 2,
  "Individual & Family Services": 92,
  "Graphics": 1,
  "Cosmetics": 68,
  "Computers": 1,
  "Crowdsourcing": 1,
  "Internet of Things": 1,
  "Nonprofits": 9,
  "Venture Capital": 1,
  "Art": 86,
  "Web CMS": 1,
  "Databases": 1,
  "Mental Health Care": 1,
  "Writing and Editing": 17,
  "Email Marketing": 2,
  "Semantic Search": 1,
  "Lead Generation": 2,
  "Government Relations": 94,
  "Home & Garden": 93,
  "Email": 1,
  "Luxury Goods & Jewelry": 95,
  "Twitter Applications": 1,
  "Real Time": 1,
  "Animation": 1,
  "Open Source": 1,
  "Electronics": 1,
  "Mobile Payments": 1,
  "Public Policy": 94,
  "Gambling & Casinos": 95,
  "Philanthropy": 96,
  "Storage": 97,
  "Career Management": 8,
  "Political Organization": 94,
  "Discounts": 98,
  "Lifestyle": 95,
  "Search Marketing": 2,
  "Marketing Automation": 2,
  "Crowdfunding": 1,
  "Hotels": 96,
  "File Sharing": 1,
  "Entrepreneur": 77,
  "Service Providers": 1,
  "Productivity Software": 1,
  "Arts and Crafts": 86,
  "Consumers": 97,
  "Trading": 79,
  "Communities": 98,
  "Think Tanks": 1,
  "Paper & Forest Products": 99,
  "App Marketing": 2,
  "Developer APIs": 1,
  "Logistics": 50,
  "Cars": 100,
  "User Experience Design": 1,
  "Public Safety": 94,
  "Audio": 101,
  "Colleges": 22,
  "Energy": 102,
  "Gift Card": 103,
  "Photo Sharing": 104,
  "Cloud Data Services": 1,
  "IT Management": 1,
  "Health Care Information Technology": 15,
  "Mobile Games": 1,
  "VoIP": 1,
  "Chat": 1,
  "Machine Learning": 1,
  "International Affairs": 1,
  "Creative": 86,
  "Social Games": 1,
  "Fine Art": 86,
  "SMS": 1,
  "Predictive Analytics": 1,
  "Public Transportation": 50,
  "Finance Technology": 3,
  "Health Diagnostics": 15,
  "Capital Markets": 3,
  "Data Security": 1,
  "Artificial Intelligence": 1,
  "Peer-to-Peer": 1,
  "Professional Services": 1,
  "Video Games": 1,
  "Travel & Tourism": 105,
  "Farming": 106,
  "Maps": 1,
  "Network Security": 1,
  "Virtualization": 1,
  "Broadcasting": 1,
  "Online Dating": 1,
  "Incentives": 1,
  "Program Development": 1,
  "Ticketing": 1,
  "Promotional": 1,
  "Business Development": 1,
  "Mobile Software Tools": 1,
  "3D": 1,
  "Data Visualization": 1,
  "Kids": 107,
  "Nanotechnology": 1,
  "Loyalty Programs": 108,
  "Identity": 137,
  "Libraries": 1,
  "Tracking": 1,
  "Recreational Facilities and Services": 15,
  "Testing": 1,
  "Tablets": 1,
  "Weddings": 109,
  "Online Rental": 110,
  "PaaS": 111,
  "Property Management": 112,
  "Data Integration": 1,
  "Environmental Innovation": 113,
  "Clean Energy": 102,
  "Advertising Platforms": 2,
  "Universities": 22,
  "Freelancers": 1,
  "Governments": 94,
  "All Students": 22,
  "Personalization": 114,
  "Beauty": 51,
  "Language Learning": 91,
  "Mobile Advertising": 2,
  "Classifieds": 115,
  "Personal Finance": 3,
  "Film": 70,
  "Optimization": 116,
  "Data Centers": 1,
  "Domains": 1,
  "Product Development Services": 1,
  "Point of Sale": 2,
  "Tourism": 105,
  "Online Travel": 105,
  "Gamification": 1,
  "Online Reservations": 106,
  "Pets": 107,
  "Supply Chain Management": 108,
  "Gps": 1,
  "Risk Management": 3,
  "Hospitals": 15,
  "Event Management": 69,
  "Document Management": 109,
  "Tech Field Support": 90,
  "Translation": 91,
  "Application Platforms": 1,
  "Interface Design": 1,
  "Auctions": 2,
  "Reputation": 110,
  "Task Management": 111,
  "Journalism": 17,
  "Local Search": 112,
  "Online Scheduling": 113,
  "aw Enforcement": 114,
  "Parenting": 107,
  "Staffing Firms": 8,
  "Stock Exchanges": 3,
  "Executive Office": 1,
  "Life Sciences": 116,
  "Shipping": 50,
  "Warehousing": 97,
  "Ediscovery": 115,
  "Energy Efficiency": 102,
  "Distribution": 117,
  "Wearables": 1,
  "Jewelry": 95,
  "Social Buying": 2,
  "Mobility": 1,
  "Direct Marketing": 2,
  "E-Commerce Platforms": 2,
  "Teachers": 15,
  "Textbooks": 118,
  "Augmented Reality": 1,
  "Green": 113,
  "Law Enforcement": 11,
  "Billing": 2,
  "Retail Technology": 2,
  "Information Security": 1,
  "Price Comparison": 2,
  "Robotics": 1,
  "Solar": 113,
  "Infrastructure": 50,
  "Renewable Energies": 113,
  "Politics": 94,
  "Image Recognition": 1,
  "Privacy": 1,
  "Bitcoin": 1,
  "Game": 1,
  "Systems": 1,
  "Wine And Spirits": 49,
  "Credit Cards": 3,
  "Agriculture": 106,
  "Collaborative Consumption": 119,
  "Sustainability": 113,
  "Charity": 120,
  "Consumer Internet": 1,
  "Healthcare Services": 15,
  "Surveys": 121,
  "Women": 122,
  "Development Platforms": 1,
  "New Product Development": 1,
  "Portals": 1,
  "Private Social Networking": 1,
  "Aerospace": 65,
  "Content Delivery": 17,
  "Mobile Health": 15,
  "Tutoring": 123,
  "Gambling": 95,
  "Glass, Ceramics & Concrete": 124,
  "IT and Cybersecurity": 1,
  "Industrial": 1,
  "Architecture": 125,
  "Home Automation": 1,
  "Monetization": 1,
  "Product Design": 1,
  "Data Mining": 1,
  "Cloud Management": 1,
  "Video on Demand": 1,
  "Ad Targeting": 2,
  "Customer Support Tools": 90,
  "Delivery": 125,
  "Sensors": 1,
  "Navigation": 1,
  "Browser Extensions": 1,
  "Cyber Security": 1,
  "Career Planning": 8,
  "Linux": 1,
  "Contact Management": 8,
  "Leisure": 126,
  "Presentations": 1,
  "Concerts": 101,
  "Food Processing": 49,
  "Group Buying": 2,
  "Incubators": 1,
  "Military": 65,
  "Virtual Worlds": 1,
  "Cloud Infrastructure": 1,
  "Subscription Businesses": 77,
  "Vacation Rentals": 96,
  "Business Analytics": 77,
  "Health and Insurance": 15,
  "Knowledge Management": 1,
  "Usability": 1,
  "mHealth": 15,
  "Digital Signage": 1,
  "Flash Storage": 1,
  "Psychology": 15,
  "Veterinary": 127,
  "Advice": 128,
  "Communications Infrastructure": 129,
  "Shipbuilding": 84,
  "Visualization": 1,
  "Opinions": 1,
  "Google Apps": 1,
  "High Schools": 22,
  "Home Renovation": 130,
  "Mobile Devices": 1,
  "Recycling": 113,
  "Rental Housing": 96,
  "3D Printing": 1,
  "Meeting Software": 1,
  "Defense": 65,
  "Electronic Health Records": 15,
  "Gadget": 1,
  "Oil": 82,
  "Postal and Courier Services": 125,
  "QR Codes": 1,
  "Semantic Web": 1,
  "Video Conferencing": 1,
  "Dairy": 1,
  "Forums": 1,
  "NFC": 1,
  "Nutrition": 68,
  "Social Recruiting": 8,
  "Social Search": 8,
  "Communications Hardware": 24,
  "Personal Health": 15,
  "Dental": 15,
  "Innovation Management": 1,
  "Content Discovery": 17,
  "Geospatial": 131,
  "Innovation Engineering": 1,
  "K-12 Education": 22,
  "Professional Networking": 8,
  "App Stores": 1,
  "IaaS": 1,
  "Lighting": 132,
  "Social Media Advertising": 2,
  "Artists Globally": 86,
  "Computer Vision": 1,
  "Doctors": 15,
  "Natural Language Processing": 1,
  "Corporate Training": 1,
  "Embedded Hardware and Software": 24,
  "Sales Automation": 2,
  "Social Bookmarking": 1,
  "Social CRM": 72,
  "Advertising Networks": 2,
  "Toys": 107,
  "Water": 84,
  "Mac": 1,
  "Performance Marketing": 2,
  "Skill Assessment": 8,
  "Shoes": 51,
  "Social Media Monitoring": 8,
  "Email Newsletters": 2,
  "Local Advertising": 2,
  "M2M": 1,
  "Office Space": 77,
  "Telephony": 1,
  "Unifed Communications": 1,
  "Judiciary": 11,
  "Package/Freight Delivery": 125,
  "Polling": 94,
  "Social Media Management": 2,
  "Alternative Medicine": 15,
  "Auto": 100,
  "Cloud Security": 1,
  "Home Decor": 133,
  "Nightlife": 134,
  "Virtual Currency": 1,
  "Craft Beer": 49,
  "Guides": 135,
  "Local Based Services": 1,
  "All Markets": 1,
  "Brokers": 3,
  "Online Video Advertising": 2,
  "Credit": 3,
  "Lead Management": 2,
  "Photo Editing": 1,
  "BPO Services": 77,
  "Engineering Firms": 1,
  "Energy Management": 102,
  "Entertainment Industry": 136,
  "Identity Management": 137,
  "Online Gaming": 1,
  "E-Books": 1,
  "Mobile Security": 1,
  "Recipes": 49,
  "Social + Mobile + Local": 1,
  "Babies": 107,
  "Intellectual Property": 11,
  "Social Television": 1,
  "Taxis": 50,
  "Outdoors": 138,
  "Physicians": 15,
  "Real Estate Investors": 4,
  "Specialty Foods": 49,
  "iPod Touch": 1,
  "3D Technology": 1,
  "DIY": 138,
  "Developer Tools": 1,
  "Mobile Video": 1,
  "Soccer": 33,
  "Celebrity": 139,
  "Contact Centers": 1,
  "Internet Service Providers": 1,
  "Virtual Workforces": 1,
  "Windows Phone 7": 1,
  "Adventure Travel": 1,
  "Business Productivity": 77,
  "Cooking": 49,
  "Human Computer Interaction": 1,
  "Intellectual Asset Management": 1,
  "MMO Games": 1,
  "MicroBlogging": 1,
  "RFID": 1,
  "Supermarkets": 49,
  "Interior Design": 1,
  "Oil & Gas": 82,
  "Social Travel": 105,
  "Match-Making": 1,
  "Social Business": 1,
  "Social Media Platforms": 1,
  "Tobacco": 140,
  "Transaction Processing": 1,
  "Bridging Online and Offline": 1,
  "CAD": 1,
  "Content Syndication": 17,
  "Enterprise 2.0": 77,
  "Fantasy Sports": 33,
  "Music Services": 101,
  "Video Chat": 1,
  "Wealth Management": 95,
  "Writers": 17,
  "Algorithms": 1,
  "Displays": 1,
  "Angels": 3,
  "Content Creators": 17,
  "Diagnostics": 15,
  "Exercise": 33,
  "Franchises": 77,
  "Groceries": 49,
  "Homeland Security": 94,
  "Mass Customization": 141,
  "Neuroscience": 15,
  "Nightclubs": 134,
  "Employer Benefits Programs": 8,
  "Enterprise Application": 1,
  "Fleet Management": 1,
  "Fraud Detection": 94,
  "Gas": 82,
  "Mobile Analytics": 1,
  "Mobile Coupons": 1,
  "Digital Entertainment": 1,
  "P2P Money Transfer": 3,
  "Certification Test": 94,
  "Interest Graph": 1,
  "Procurement": 142,
  "Railroad Manufacture": 143,
  "Test and Measurement": 145,
  "Contests": 146,
  "Educational Games": 22,
  "Licensing": 147,
  "Mobile Social": 1,
  "Clinical Trials": 15,
  "Emerging Markets": 77,
  "Flash Sales": 2,
  "Mobile Enterprise": 1,
  "Organic Food": 49,
  "Social Fundraising": 1,
  "Text Analytics": 1,
  "Biometrics": 15,
  "Electrical Distribution": 1,
  "Therapeutics": 15,
  "Web Presence Management": 1,
  "Digital Rights Management": 1,
  "Humanitarian": 148,
  "Internet TV": 17,
  "Lifestyle Products": 95,
  "Synchronization": 1,
  "Cable": 1,
  "Spas": 1,
  "Batteries": 1,
  "Collectibles": 1,
  "Comparison Shopping": 87,
  "Drones": 1,
  "Flowers": 1,
  "Coffee": 49,
  "Designers": 1,
  "Freemium": 1,
  "Music Venues": 101,
  "Proximity Internet": 1,
  "Trusted Networks": 1,
  "DOD/Military": 65,
  "Diabetes": 15,
  "Enterprise Search": 1,
  "Visual Search": 1,
  "Bio-Pharm": 15,
  "Charter Schools": 22,
  "Coworking": 1,
  "Hedge Funds": 3,
  "Mechanical Solutions": 1,
  "Mining Technologies": 1,
  "Online Auctions": 1,
  "Organic": 113,
  "Realtors": 4,
  "Oil and Gas": 82,
  "Creative Industries": 86,
  "Enterprise Security": 1,
  "Fishery": 49,
  "Smart Grid": 1,
  "Video Editing": 1,
  "Financial Exchanges": 3,
  "Internet Radio Market": 17,
  "Mobile Shopping": 87,
  "Simulation": 1,
  "University Students": 22,
  "Application Performance Monitoring": 1,
  "Government Innovation": 94,
  "Impact Investing": 1,
  "Local Services": 77,
  "Mens Specific": 150,
  "Online Education": 22,
  "Self Development": 1,
  "Smart Building": 1,
  "Speech Recognition": 1,
  "Sponsorship": 3,
  "Web Browsers": 1,
  "Young Adults": 1,
  "Business Information Systems": 1,
  "Cannabis": 49,
  "English-Speaking": 91,
  "Families": 107,
  "Handmade": 151,
  "Infrastructure Builders": 152,
  "Legislative Office": 11,
  "Mobile Emergency&Health": 15,
  "Plumbers": 153,
  "********************************************************************** checked until here ": 10000,
  "Internet Technology": 1,
  "Teenagers": 107,
  "Independent Music Labels": 101,
  "Kinect": 1,
  "Limousines": 100,
  "Medical Professionals": 15,
  "Virtual Goods": 1,
  "Data Center Infrastructure": 1,
  "Enterprise Resource Planning": 1,
  "New Technologies": 1,
  "Online Identity": 137,
  "Religion": 73,
  "Social Entrepreneurship": 1,
  "Social News": 1,
  "Direct Sales": 2,
  "Lasers": 1,
  "Operating Systems": 1,

  "Personal Branding": 2,
  "Film Production": 70,
  "College Recruiting": 8,
  "Advertising Exchanges": 2,
  "College Campuses": 22,
  "Eyewear": 1,
  "Landscaping": 154,
  "Lingerie": 155,
  "Multi-level Marketing": 2,
  "Registrars": 156,
  "Sunglasses": 51,
  "Surfing Community": 157,
  "Tea": 49,
  "B2B Express Delivery": 125,
  "Cyber": 1,
  "Elder Care": 168,
  "Governance": 94,
  "Intelligent Systems": 1,
  "Material Science": 158,
  "Quantified Self": 159,
  "Resorts": 160,
  "Shared Services": 161,
  "Early-Stage Technology": 1,
  "Home Owners": 4,
  "PC Gaming": 1,
  "Product Search": 1,
  "Recreation": 162,
  "Residential Solar": 1,
  "Spam Filtering": 1,
  "TV Production": 17,
  "Consumer Lending": 163,
  "Human Resource Automation": 1,
  "Logistics Company": 50,
  "Racing": 100,
  "Ranching": 106,
  "Temporary Staffing": 8,
  "Alumni": 22,
  "Business Travelers": 77,
  "Carbon": 1,
  "Cryptocurrency": 1,
  "Deep Information Technology": 1,
  "Energy IT": 102,
  "Game Mechanics": 1,
  "Genetic Testing": 1,
  "Green Consumer Goods": 113,
  "High School Students": 22,
  "Hip Hop": 101,
  "Insurance Companies": 164,
  "Personal Data": 165,
  "Renewable Tech": 113,
  "Ventures for Good": 166,
  "Advanced Materials": 167,
  "Animal Feed": 127,
  "Assisted Living": 168,
  "Civil Engineers": 169,
  "Data Privacy": 1,
  "Debt Collecting": 3,
  "Electric Vehicles": 1,
  "Film Distribution": 70,
  "General Public Worldwide": 94,
  "Internet Infrastructure": 1,
  "Local Commerce": 77,
  "Mobile Infrastructure": 1,
  "Moneymaking": 3,
  "Space Travel": 65,
  "Subscription Service": 170,
  "Wind": 113,
  "Bioinformatics": 1,
  "Comics": 171,
  "Custom Retail": 2,
  "EBooks": 1,
  "Enterprise Hardware": 24,
  "Gift Exchange": 171,
  "Indians": 172,
  "Mobile Search": 1,
  "Motion Capture": 1,
  "Musical Instruments": 101,
  "Natural Gas Uses": 82,
  "Niche Specific": 173,
  "Physical Security": 53,
  "Productivity": 174,
  "Q&A": 175,
  "Rehabilitation": 15,
  "Senior Health": 15,
  "Social Investing": 1,
  "Social Media Agent": 1,
  "Sports Stadiums": 33,
  "Twin-Tip Skis": 176,
  "User Testing": 1,
  "Watch": 1,
  "App Discovery": 1,
  "Assisitive Technology": 1,
  "Baby Accessories": 107,
  "Child Care": 107,
  "Cloud-Based Music": 101,
  "Diving": 33,
  "Edutainment": 22,
  "Energy Storage": 102,
  "Green Building": 113,
  "Music Education": 2,
  "Outdoor Advertising": 2,
  "Service Industries": 77,
  "TV Station": 17,
  "Boating Industry": 84,
  "Motors": 100,
  "RIM": 177,
  "Semiconductor Manufacturing Equipment": 24,
  "Social Opinion Platform": 1,
  "User Interface": 1,
  "Video Processing": 1,
  "WebOS": 1,
  "Anything Capital Intensive": 3,
  "Baby Safety": 107,
  "Brewing": 49,
  "Charities": 120,
  "Console Gaming": 1,
  "Data Center Automation": 1,
  "Fuels": 82,
  "Gift Registries": 171,
  "Google Glass": 1,
  "Homeless Shelter": 172,
  "Industrial Energy Efficiency": 102,
  "Medication Adherence": 15,
  "Minerals": 173,
  "Musicians": 101,
  "Reading Apps": 1,
  "Specialty Chemicals": 68,
  "Teaching STEM Concepts": 174,
  "Audiobooks": 101,
  "Biomass Power Generation": 175,
  "Building Owners": 4,
  "Casual Games": 1,
  "Cause Marketing": 2,
  "Clean Technology IT": 1,
  "Commercial Solar": 113,
  "Concentrated Solar Power": 113,
  "Experience Design": 1,
  "Face Recognition": 1,
  "Field Support Services": 90,
  "Gay & Lesbian": 174,
  "Group Email": 2,
  "Independent Pharmacies": 15,
  "Lifestyle Businesses": 95,
  "Nutraceutical": 68,
  "Optical Communications": 1,
  "Pre Seed": 1,
  "Private School": 22,
  "Self Storage": 97,
  "South East Asia": 175,
  "Unmanned Air Systems": 65,
  "Video Game Tournaments": 1,
  "Virtual Desktop": 1,
  "Biofuels": 82,
  "China Internet": 1,
  "Disruptive Models": 176,
  "Farmers Market": 106,
  "Fertility": 106,
  "Fmcg": 177,
  "Funeral Industry": 178,
  "GreenTech": 113,
  "Group SMS": 2,
  "Health Services Industry": 15,
  "Independent Music": 101,
  "Mac Applications": 1,
  "Notebooks": 1,
  "Quantitative Marketing": 2,
  "Radical Breakthrough Startups": 1,
  "Remediation": 179,
  "Ride Sharing": 50,
  "Sailing Community": 84,
  "Shipping Broker Industry": 3,
  "Social Activists": 1,
  "Swimming": 33,
  "Technical Continuing Education": 22,
  "Vending and Concessions": 2,
  "West Africa": 180,
  "Aquaculture": 184,
  "Cloud Gaming": 1,
  "Direct Advertising": 2,
  "EDA Tools": 1,
  "East Africa": 185,
  "Elderly": 168,
  "Golf Equipment": 33,
  "Invention": 186,
  "Low Bid Auctions": 2,
  "Military Deployment": 65,
  "Mothers": 107,
  "Podcast": 1,
  "Prediction Markets": 187,
  "Salesforce Killers": 2,
  "Serious Games": 1,
  "Skill Gaming": 1,
  "Timeshares": 1,
  "UV LEDs": 1,
  "Adaptive Equipment": 1,
  "Air Pollution Control": 113,
  "Baby Boomers": 107,
  "Biotechnology and Semiconductor": 24,
  "Enterprise Purchasing": 77,
  "First Aid": 15,
  "Fruit": 49,
  "Fuel Cells": 82,
  "Generation Y-Z": 107,
  "Hunting Industry": 189,
  "Labor Optimization": 190,
  "Land Developers": 191,
  "Lotteries": 192,
  "Made in Italy": 193,
  "Micro-Enterprises": 77,
  "Penetration Testing": 1,
  "Pervasive Computing": 1,
  "Underserved Children": 107,
  "Utility Land Vehicles": 194,
  "Vulnerability Management": 195
}