exports.industries = {
  "Information Technology and Services": 1,
  "Computer Software": 1,
  "Software": 1,
  "Marketing and Advertising": 2,
  "Internet": 1,
  "Financial Services": 3,
  "Real Estate": 4,
  "Mobile": 1,
  "Telecommunications": 5,
  "Management Consulting": 6,
  "E-Commerce": 7,
  "Staffing and Recruiting": 8,
  "Curated Web": 1,
  "Advertising": 2,
  "Non-Profit Organization Management": 9,
  "Design": 10,
  "Law Practice": 11,
  "Social Media": 1,
  "Consulting": 12,
  "Higher Education": 13,
  "Construction": 14,
  "Hospital & Health Care": 15,
  "Insurance": 16,
  "Human Resources": 8,
  "Publishing": 17,
  "Retail": 18,
  "Enterprise Software": 1,
  "Entertainment": 19,
  "Banking": 3,
  "Biotechnology": 20,
  "Automotive": 21,
  "Web Development": 1,
  "Education Management": 22,
  "Education": 22,
  "Games": 1,
  "Hospitality": 23,
  "Electrical/Electronic Manufacturing": 24,
  "Government Administration": 25,
  "Investment Management": 26,
  "Finance": 3,
  "Public Relations and Communications": 2,
  "SaaS": 1,
  "Music": 27,
  "Architecture & Planning": 28,
  "Accounting": 3,
  "Pharmaceuticals": 15,
  "Consumer Goods": 30,
  "Oil & Energy": 31,
  "Professional Training & Coaching": 32,
  "Medical Devices": 15,
  "Sports": 33,
  "Technology": 1,
  "Apps": 1,
  "SEO": 1,
  "Web Design": 1,
  "Analytics": 34,
  "Broadcast Media": 35,
  "Printing": 36,
  "Sales and Marketing": 2,
  "Health, Wellness and Fitness": 37,
  "Leisure, Travel & Tourism": 38,
  "Media Production": 35,
  "Mechanical or Industrial Engineering": 39,
  "Research": 40,
  "Fund-Raising": 41,
  "Semiconductors": 24,
  "Legal Services": 11,
  "Venture Capital & Private Equity": 41,
  "Search": 42,
  "Hardware + Software": 1,
  "Health and Wellness": 1,
  "Internet Marketing": 2,
  "Web Hosting": 1,
  "Environmental Services": 43,
  "News": 44,
  "Consumer Electronics": 45,
  "Public Relations": 2,
  "Market Research": 46,
  "Networking": 47,
  "Online Media": 35,
  "Health Care": 15,
  "Photography": 48,
  "Cloud Computing": 1,
  "Media": 35,
  "Food & Beverages": 49,
  "Logistics and Supply Chain": 50,
  "Fashion": 51,
  "Android": 1,
  "Travel": 38,
  "Video": 52,
  "Wireless": 1,
  "Security": 53,
  "Startups": 54,
  "Computer & Network Security": 1,
  "iPhone": 1,
  "Transportation/Trucking/Railroad": 50,
  "Civil Engineering": 55,
  "Computer Hardware": 1,
  "Apparel & Fashion": 51,
  "Information Technology": 1,
  "Information Services": 1,
  "Computer Games": 56,
  "Marketplaces": 57,
  "Business Services": 58,
  "Services": 59,
  "Machinery": 60,
  "Computer Networking": 1,
  "iOS": 1,
}